version: '3.9'

services:
  app:
      build: .
      ports:
        - '${APP_PORT:-8082}:8080'
      restart: on-failure
      depends_on:
        - mysql
        - redis
      networks:
        - networkapp

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${DB_PORT:-33066}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql-db:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    networks:
      - networkapp

  redis:
    image: redis:alpine3.18
    ports:
      - '${REDIS_PORT:-6379}:6379'
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    volumes:
      - 'redis-db:/data'
    networks:
      - networkapp

volumes:
  mysql-db:
  redis-db:

networks:
  networkapp:
    driver: bridge