// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "lucio.com/order-service/src/domain/entities"
)

// CampaignRepository is an autogenerated mock type for the CampaignRepository type
type CampaignRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: store
func (_m *CampaignRepository) Create(store entities.Campaign) (*entities.Campaign, error) {
	ret := _m.Called(store)

	var r0 *entities.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Campaign) (*entities.Campaign, error)); ok {
		return rf(store)
	}
	if rf, ok := ret.Get(0).(func(entities.Campaign) *entities.Campaign); ok {
		r0 = rf(store)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.Campaign) error); ok {
		r1 = rf(store)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ID
func (_m *CampaignRepository) FindByID(ID uint) *entities.Campaign {
	ret := _m.Called(ID)

	var r0 *entities.Campaign
	if rf, ok := ret.Get(0).(func(uint) *entities.Campaign); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Campaign)
		}
	}

	return r0
}

// NewCampaignRepository creates a new instance of CampaignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCampaignRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CampaignRepository {
	mock := &CampaignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
