// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dto "lucio.com/order-service/src/domain/dto"
)

// CreateBranchUC is an autogenerated mock type for the CreateBranchUC type
type CreateBranchUC struct {
	mock.Mock
}

// Execute provides a mock function with given fields: createBranchDTO
func (_m *CreateBranchUC) Execute(createBranchDTO dto.CreateBranchDTO) (*dto.BranchCreatedDTO, error) {
	ret := _m.Called(createBranchDTO)

	var r0 *dto.BranchCreatedDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateBranchDTO) (*dto.BranchCreatedDTO, error)); ok {
		return rf(createBranchDTO)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateBranchDTO) *dto.BranchCreatedDTO); ok {
		r0 = rf(createBranchDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BranchCreatedDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CreateBranchDTO) error); ok {
		r1 = rf(createBranchDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreateBranchUC creates a new instance of CreateBranchUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateBranchUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateBranchUC {
	mock := &CreateBranchUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
