// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dto "lucio.com/order-service/src/domain/dto"
)

// CreateBranchCampaignUC is an autogenerated mock type for the CreateBranchCampaignUC type
type CreateBranchCampaignUC struct {
	mock.Mock
}

// Execute provides a mock function with given fields: createBranchCampaignDTO
func (_m *CreateBranchCampaignUC) Execute(createBranchCampaignDTO dto.CreateBranchCampaignDTO) (*dto.BranchCampaignCreatedDTO, error) {
	ret := _m.Called(createBranchCampaignDTO)

	var r0 *dto.BranchCampaignCreatedDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateBranchCampaignDTO) (*dto.BranchCampaignCreatedDTO, error)); ok {
		return rf(createBranchCampaignDTO)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateBranchCampaignDTO) *dto.BranchCampaignCreatedDTO); ok {
		r0 = rf(createBranchCampaignDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BranchCampaignCreatedDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CreateBranchCampaignDTO) error); ok {
		r1 = rf(createBranchCampaignDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreateBranchCampaignUC creates a new instance of CreateBranchCampaignUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateBranchCampaignUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateBranchCampaignUC {
	mock := &CreateBranchCampaignUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
