// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dto "lucio.com/order-service/src/domain/dto"
)

// GetBranchCampaignsUC is an autogenerated mock type for the GetBranchCampaignsUC type
type GetBranchCampaignsUC struct {
	mock.Mock
}

// Execute provides a mock function with given fields: branchID
func (_m *GetBranchCampaignsUC) Execute(branchID uint) []dto.BranchCampaignReportDTO {
	ret := _m.Called(branchID)

	var r0 []dto.BranchCampaignReportDTO
	if rf, ok := ret.Get(0).(func(uint) []dto.BranchCampaignReportDTO); ok {
		r0 = rf(branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.BranchCampaignReportDTO)
		}
	}

	return r0
}

// NewGetBranchCampaignsUC creates a new instance of GetBranchCampaignsUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetBranchCampaignsUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetBranchCampaignsUC {
	mock := &GetBranchCampaignsUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
