// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "lucio.com/order-service/src/domain/entities"
)

// RewardRepository is an autogenerated mock type for the RewardRepository type
type RewardRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: reward
func (_m *RewardRepository) Create(reward entities.Reward) (*entities.Reward, error) {
	ret := _m.Called(reward)

	var r0 *entities.Reward
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Reward) (*entities.Reward, error)); ok {
		return rf(reward)
	}
	if rf, ok := ret.Get(0).(func(entities.Reward) *entities.Reward); ok {
		r0 = rf(reward)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Reward)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.Reward) error); ok {
		r1 = rf(reward)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRewardRepository creates a new instance of RewardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRewardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RewardRepository {
	mock := &RewardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
